import { IProject } from 'types/projects.types'

export const PROJECTS: IProject[] = [
  {
    title: 'Chat App',
    description: 'Real-time chat application.',
    keywords: [
      'React',
      'Typescript',
      'RTK Query',
      'Material UI',
      'React Hook Form',
      'React Testing Library',
      'Socket.IO',
      'Vite',
      'Jest',
    ],
    url: 'https://chat.brianmatthewsmith.com',
    github: 'https://github.com/bsmith-code/chat',
  },
  {
    title: 'SSO Auth',
    description: 'User Authentication & Authorization.',
    keywords: [
      'React',
      'Typescript',
      'RTK Query',
      'Material UI',
      'React Hook Form',
      'React Testing Library',
      'Vite',
      'Jest',
    ],
    url: 'https://auth.brianmatthewsmith.com',
    github: 'https://github.com/bsmith-code/auth',
  },
  {
    title: 'Pokedex',
    description: 'Search for a Pokémon by name.',
    keywords: [
      'React',
      'Typescript',
      'RTK Query',
      'Material UI',
      'React Hook Form',
      'React Testing Library',
      'Vite',
      'Jest',
    ],
    url: 'https://pokedex.brianmatthewsmith.com',
    github: 'https://github.com/bsmith-code/pokedex',
  },
  {
    title: 'Study Guide',
    description:
      'Flash card system used to master the art of frontend engineering.',
    keywords: [
      'React',
      'Typescript',
      'RTK Query',
      'Material UI',
      'React Hook Form',
      'React Testing Library',
      'Vite',
      'Jest',
    ],
    url: 'https://brianmatthewsmith.com/study',
    github: 'https://github.com/bsmith-code/portfolio',
  },
]
